### ISSUE TITLE
Define the MVP

### ISSUE THREAD

**Issue by Javiercerna** [chingu-voyages/v11-geckos-team-13#1]
Define your MVP by:

- [x] Creating a simple, concise statement of what your application will achieve and the value it has to its users. This is your North Star. Every function and feature in the application should reinforce this goal. (#2)
- [x] Listing the functions you want to include in the application. Prioritize them by identifying which are needs and which are wants. (#3)
- [x] Listing the features in each function and prioritize them in the same manner. Identify which are needs and which are wants. (#3)
- [x] Defining the attributes and roles of your end users and matching them to your features and functions. This helps ensure that the app will have a logical flow, and more importantly, that it meets all user needs.
- [x] Adding the tasks needed to reach MVP status to your project backlog. Since you'll be following Agile principles, the backlog won't be complete until the latter part of the project. The team will continuously revise it in each sprint.

**Comment by Javiercerna** [comment]
Closed! Let the project begin :smile:
