### ISSUE TITLE
Feature: Pomodoro

### ISSUE THREAD

**Issue by Javiercerna** [chingu-voyages/v11-geckos-team-13#14]
As a user, I want to have a pomodoro timer so I can plan work in intervals.

**Acceptance criteria**
Users should be able to:

- [ ] Start, stop and reset the pomodoro #9 
- [ ] Set the time of each interval (default 25 minutes, minimum 1 minute, maximum 24 hours) #10 
- [ ] Add a break timer if they need to, and set the time of the break (default 5 minutes, minimum 1 minute, maximum 24 hours) #11 
- [ ] Continue working on the Pomodoro even if the tab is refreshed or a new tab is opened #12 
- [ ] Show/hide the pomodoro widget #13
