### ISSUE TITLE
Feature: Weather

### ISSUE THREAD

**Issue by Javiercerna** [chingu-voyages/v11-geckos-team-13#22]
As a user, I want to check the weather for today and tomorrow so I can plan appropriately before going out.

**Acceptance criteria**
Users should be able to:
- [ ] Choose a location manually and save it #16 
- [ ] Allow the browser to select their location and save it (if they want to, otherwise default to the first criterion) #17 
- [ ] Check the weather for today and tomorrow using 3 hour intervals #18 
- [ ] Check the following weather parameters: temperature, windspeed, whether it's raining or not #19 
- [ ] Check the temperature both in °C and °F, the windspeed both in m/s and km/h #20 
- [ ] Show/hide the weather widget #21
