### ISSUE TITLE
Feature: Currency converter

### ISSUE THREAD

**Issue by Javiercerna** [chingu-voyages/v11-geckos-team-13#27]
As a user, I want to have a currency converter so I can make currency conversions with the updated rates.

**Acceptance criteria**
Users should be able to:
- [ ] Select two currencies (input currency, output currency) #23 
- [ ] Invert the currencies (input now becomes output and vice versa) #24 
- [ ] Check the currency rate being used #25 
- [ ] Show/hide the currency converter widget #26
