### ISSUE TITLE
Feature: Google Calendar

### ISSUE THREAD

**Issue by Javiercerna** [chingu-voyages/v11-geckos-team-13#32]
As a user, I want to have a calendar so I can plan my activities for the day.

**Acceptance criteria**
Users should be able to:
- [ ] Check the events happening today on the calendar #28 
- [ ] Add events to today’s calendar by providing the following as input: name of the new event, hours, calendar name #29 
- [ ] Remove events from today’s calendar (ask for confirmation to prevent accidental deletes) #30 
- [ ] Show/hide the calendar widget #31
